### ISSUE TITLE
provision fails if jenkins package is not pre-installed

### ISSUE THREAD

**Issue by unclespeedo** [pgr0ss/puppet-jenkins#1]
(puppet provision debug output at end of email)

Just thought I'd mention that I was testing your module on a vanilla install of Ubuntu Precise. FWIW, I'm deploying with vagrant in a vmware fusion VM.

The errors go away if I manually install the jenkins package, it appears that files.pp is loading first but should depend on the jenkins package being installed.

I have not gotten very deep in my troubleshooting, hopefully I haven't overlooked anything obvious.

Cheers,
Ryan

[default] Running provisioner: puppet...
Running Puppet with default.pp...
stdin: is not a tty
Info: Loading facts in /tmp/vagrant-puppet-1/modules-0/jenkins/lib/facter/jenkins_version.rb
Info: Loading facts in /tmp/vagrant-puppet-1/modules-0/stdlib/lib/facter/facter_dot_d.rb
Info: Loading facts in /tmp/vagrant-puppet-1/modules-0/stdlib/lib/facter/pe_version.rb
Info: Loading facts in /tmp/vagrant-puppet-1/modules-0/stdlib/lib/facter/puppet_vardir.rb
Info: Loading facts in /tmp/vagrant-puppet-1/modules-0/stdlib/lib/facter/root_home.rb
Debug: importing '/tmp/vagrant-puppet-1/modules-0/jenkins/manifests/init.pp' in environment production
Debug: Automatically imported jenkins from jenkins into production
Debug: importing '/tmp/vagrant-puppet-1/modules-0/jenkins/manifests/files.pp' in environment production
Debug: Automatically imported jenkins::files from jenkins/files into production
Debug: Scope(Class[Jenkins::Files]): Retrieving template jenkins/config.xml.erb
Debug: template[/tmp/vagrant-puppet-1/modules-0/jenkins/templates/config.xml.erb]: Bound template variables for /tmp/vagrant-puppet-1/modules-0/jenkins/templates/config.xml.erb in 0.00 seconds
Error: Failed to parse template jenkins/config.xml.erb:
  Filepath: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.0.2/lib/puppet/parser/templatewrapper.rb
  Line: 70
  Detail: Could not find value for 'jenkins_version' at /tmp/vagrant-puppet-1/modules-0/jenkins/templates/config.xml.erb:4
 at /tmp/vagrant-puppet-1/modules-0/jenkins/manifests/files.pp:12 on node liquify-build.localdomain
Error: Failed to parse template jenkins/config.xml.erb:
  Filepath: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.0.2/lib/puppet/parser/templatewrapper.rb
  Line: 70
  Detail: Could not find value for 'jenkins_version' at /tmp/vagrant-puppet-1/modules-0/jenkins/templates/config.xml.erb:4
 at /tmp/vagrant-puppet-1/modules-0/jenkins/manifests/files.pp:12 on node liquify-build.localdomain
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet apply --verbose --debug --modulepath '/etc/puppet/modules:/tmp/vagrant-puppet-1/modules-0' --manifestdir /tmp/vagrant-puppet-1/manifests --detailed-exitcodes /tmp/vagrant-puppet-1/manifests/default.pp || [ $? -eq 2 ]

Stdout from the command:

Info: Loading facts in /tmp/vagrant-puppet-1/modules-0/jenkins/lib/facter/jenkins_version.rb
Info: Loading facts in /tmp/vagrant-puppet-1/modules-0/stdlib/lib/facter/facter_dot_d.rb
Info: Loading facts in /tmp/vagrant-puppet-1/modules-0/stdlib/lib/facter/pe_version.rb
Info: Loading facts in /tmp/vagrant-puppet-1/modules-0/stdlib/lib/facter/puppet_vardir.rb
Info: Loading facts in /tmp/vagrant-puppet-1/modules-0/stdlib/lib/facter/root_home.rb
Debug: importing '/tmp/vagrant-puppet-1/modules-0/jenkins/manifests/init.pp' in environment production
Debug: Automatically imported jenkins from jenkins into production
Debug: importing '/tmp/vagrant-puppet-1/modules-0/jenkins/manifests/files.pp' in environment production
Debug: Automatically imported jenkins::files from jenkins/files into production
Debug: Scope(Class[Jenkins::Files]): Retrieving template jenkins/config.xml.erb
Debug: template[/tmp/vagrant-puppet-1/modules-0/jenkins/templates/config.xml.erb]: Bound template variables for /tmp/vagrant-puppet-1/modules-0/jenkins/templates/config.xml.erb in 0.00 seconds

Stderr from the command:

stdin: is not a tty
Error: Failed to parse template jenkins/config.xml.erb:
  Filepath: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.0.2/lib/puppet/parser/templatewrapper.rb
  Line: 70
  Detail: Could not find value for 'jenkins_version' at /tmp/vagrant-puppet-1/modules-0/jenkins/templates/config.xml.erb:4
 at /tmp/vagrant-puppet-1/modules-0/jenkins/manifests/files.pp:12 on node liquify-build.localdomain
Error: Failed to parse template jenkins/config.xml.erb:
  Filepath: /opt/ruby/lib/ruby/gems/1.9.1/gems/puppet-3.0.2/lib/puppet/parser/templatewrapper.rb
  Line: 70
  Detail: Could not find value for 'jenkins_version' at /tmp/vagrant-puppet-1/modules-0/jenkins/templates/config.xml.erb:4
 at /tmp/vagrant-puppet-1/modules-0/jenkins/manifests/files.pp:12 on node liquify-build.localdomain

**Comment by pgr0ss** [comment]
It looks like the fact is failing if jenkins is not installed. There's a rescue on the fact, but I guess it's not working:

https://github.com/pgr0ss/puppet-jenkins/blob/283b8534beb8dd405eecd18f10202c3110e2b739/lib/facter/jenkins_version.rb#L6

Can you try returning 0 instead of nil and see if the problem goes away? In any case, it looks like it requires at least two puppet runs, since the first won't have the package and can't get the correct version of jenkins. The second run will put the right version number into the config files.

I'm not sure what the right fix is here. Let me research it a bit.

**Comment by unclespeedo** [comment]
Thanks @pgr0ss, I changed nil to 0 and that gets me further on the first run

The second run is successful.

> Error: /bin/sh -c 'cd /var/lib/jenkins/plugins && wget http://updates.jenkins-ci.org/download/plugins/git/1.1.26/git.hpi' returned 2 instead of one of [0]
> Error: /Stage[main]/Jenkins::Package/Exec[git-plugin]/returns: change from notrun to 0 failed: /bin/sh -c 'cd /var/lib/jenkins/plugins && wget http://updates.jenkins-ci.org/download/plugins/git/1.1.26/git.hpi' returned 2 instead of one of [0]
> Warning: /Stage[main]/Jenkins::Files/File[/var/lib/jenkins/plugins]: Skipping because of failed dependencies
> Warning: /Stage[main]/Jenkins::Files/File[/var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml]: Skipping because of failed dependencies
> Warning: /Stage[main]/Jenkins::Files/File[/var/lib/jenkins/jobs]: Skipping because of failed dependencies
> Warning: /Stage[main]/Jenkins::Files/File[/var/lib/jenkins/config.xml]: Skipping because of failed dependencies
> Warning: /Stage[main]//Jenkins::Plugin[github]/Exec[download-github]: Skipping because of failed dependencies
> Warning: /Stage[main]//Jenkins::Plugin[sbt]/Exec[download-sbt]: Skipping because of failed dependencies
> Warning: /Stage[main]/Jenkins::Service/Service[jenkins]: Skipping because of failed dependencies

**Comment by pgr0ss** [comment]
Great. Do you want to submit a pull request for the change?
