### ISSUE TITLE
Error passing

### ISSUE THREAD

**Issue by ghost** [pgr0ss/puppet-jenkins#4]
`node "jenkins-master" {
  class { jenkins:
    url => "http://ci.example.com",
    email_address => "ci@example.com",
    slaves => ["jenkins-slave01", "jenkins-slave02"],
    views => [
      ["All", ".*"],
      ["Master", ".*master.*"],
      ["Release", ".*release.*"],
    ]
  }`

when i add this to my nodes.pp file it tells me i need to still pass url, etc to jenkins class. i could be using it wrong i am new to puppet

**Comment by pgr0ss** [comment]
I haven't updated or used this puppet module in a while, so it's possible there's an issue with it on newer version of puppet.

**Comment by ghost** [comment]
so all that is actually correct apparently, you just can't pass member variables that are not prefixed with the @ symbol in new versions
